<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="79886" started-at="2023-04-30T04:19:04Z" finished-at="2023-04-30T04:20:24Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="79886" started-at="2023-04-30T04:19:04Z" finished-at="2023-04-30T04:20:24Z">
      <class name="TestCases.LoginTest">
        <test-method status="PASS" signature="ReportSetup()[pri:0, instance:TestCases.LoginTest@6591f517]" name="ReportSetup" is-config="true" duration-ms="981" started-at="2023-04-30T04:19:04Z" finished-at="2023-04-30T04:19:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportSetup -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:TestCases.LoginTest@6591f517]" name="SetUp" is-config="true" duration-ms="12592" started-at="2023-04-30T04:19:05Z" finished-at="2023-04-30T04:19:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.LoginTest.test1() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="test1()[pri:0, instance:TestCases.LoginTest@6591f517]" name="test1" duration-ms="21763" started-at="2023-04-30T04:19:17Z" finished-at="2023-04-30T04:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:TestCases.LoginTest@6591f517]" name="TearDown" is-config="true" duration-ms="806" started-at="2023-04-30T04:19:39Z" finished-at="2023-04-30T04:19:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:TestCases.LoginTest@6591f517]" name="SetUp" is-config="true" duration-ms="6274" started-at="2023-04-30T04:19:40Z" finished-at="2023-04-30T04:19:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.LoginTest.test2() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="test2()[pri:0, instance:TestCases.LoginTest@6591f517]" name="test2" duration-ms="24514" started-at="2023-04-30T04:19:46Z" finished-at="2023-04-30T04:20:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:TestCases.LoginTest@6591f517]" name="TearDown" is-config="true" duration-ms="1240" started-at="2023-04-30T04:20:11Z" finished-at="2023-04-30T04:20:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:TestCases.LoginTest@6591f517]" name="SetUp" is-config="true" duration-ms="8526" started-at="2023-04-30T04:20:12Z" finished-at="2023-04-30T04:20:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.LoginTest.test4() throws com.codoid.products.exception.FilloException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="test4()[pri:0, instance:TestCases.LoginTest@6591f517]" name="test4" duration-ms="625" started-at="2023-04-30T04:20:20Z" finished-at="2023-04-30T04:20:21Z">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[data table is not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: data table is not found
at com.codoid.products.fillo.SelectExcelUtil.runSelectQuery(SelectExcelUtil.java:57)
at com.codoid.products.fillo.Select.getRecordset(Select.java:61)
at com.codoid.products.fillo.Connection.executeQuery(Connection.java:64)
at TestCases.LoginTest.test4(LoginTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:TestCases.LoginTest@6591f517]" name="TearDown" is-config="true" duration-ms="1207" started-at="2023-04-30T04:20:21Z" finished-at="2023-04-30T04:20:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="ReportClean()[pri:0, instance:TestCases.LoginTest@6591f517]" name="ReportClean" is-config="true" duration-ms="1304" started-at="2023-04-30T04:20:22Z" finished-at="2023-04-30T04:20:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportClean -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
